# Generated by Django 5.2 on 2025-04-27 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_address_user_rename_comment_review_review_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number_of_reviews',
        ),
    ]
