# Generated by Django 5.2 on 2025-05-08 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewsreview',
            options={},
        ),
    ]
