# Generated by Django 5.2 on 2025-05-08 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_reviewsreview_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewsreview',
            name='pk',
        ),
        migrations.AddField(
            model_name='reviewsreview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='reviewsreview',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reviews.reviewsstore'),
        ),
        migrations.AddField(
            model_name='reviewsreview',
            name='user',
            field=models.TextField(default='test'),
        ),
        migrations.AlterModelTable(
            name='reviewsreview',
            table=None,
        ),
    ]
