# Generated by Django 5.2 on 2025-05-08 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_remove_reviewsreview_pk_reviewsreview_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewsreview',
            options={'managed': False},
        ),
    ]
