# Generated by Django 5.2 on 2025-05-08 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_reviewsreview_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reviewsreview',
            table='reviews_review',
        ),
    ]
